'use client';
import { useEffect, useState } from 'react';
import { Bot, Eye, EyeOff, Loader2, Pencil, Plus, Save, TestTube2, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { ManagePageHeader } from '@/components/manage-page-header';
import { AiAbilitiesPanel, type AbilityValues } from '@/components/ai-abilities-panel';
import { AiUsageSummary, type AiUsageSummaryValue } from '@/components/ai-usage-summary';
import { ProjectMemoryManager } from '@/components/project-memory-manager';

interface Profile { id: string; name: string; provider: string; baseUrl: string; model: string; apiKeyHint: string; readOnly?: boolean }
interface Preferences { responseStyle: 'concise' | 'standard' | 'detailed'; attendanceMetric: 'both' | 'headcount' | 'personDays'; showSources: boolean; memoryEnabled: boolean; customInstructions: string; abilities: AbilityValues }
const defaultPreferences: Preferences = { responseStyle: 'standard', attendanceMetric: 'both', showSources: true, memoryEnabled: true, customInstructions: '', abilities: { dailyReport: true, attendanceAnalysis: true, progressAnalysis: true, anomalyAnalysis: true, knowledgeQa: true } };
interface ResponseData { source: 'system' | 'environment' | 'none'; activeProfileId: string; fallbackProfileId: string | null; profiles: Profile[]; preferences: Preferences; usage: AiUsageSummaryValue; error?: string }
const presets = [
  { provider: 'DeepSeek', baseUrl: 'https://api.deepseek.com/v1', model: 'deepseek-chat' },
  { provider: 'OpenAI', baseUrl: 'https://api.openai.com/v1', model: 'gpt-4o-mini' },
  { provider: '通义千问', baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1', model: 'qwen-plus' },
  { provider: '豆包', baseUrl: 'https://ark.cn-beijing.volces.com/api/v3', model: '' },
];

export default function AiSettingsPage() {
  const [data, setData] = useState<ResponseData>({ source: 'none', activeProfileId: '', fallbackProfileId: null, profiles: [], preferences: defaultPreferences, usage: { total: 0, successRate: 0, fallbackCount: 0, averageDurationMs: 0, models: [] } });
  const [preferences, setPreferences] = useState<Preferences>(defaultPreferences);
  const [loading, setLoading] = useState(true); const [working, setWorking] = useState(''); const [editingId, setEditingId] = useState(''); const [showForm, setShowForm] = useState(false); const [showKey, setShowKey] = useState(false);
  const [name, setName] = useState(''); const [provider, setProvider] = useState('DeepSeek'); const [apiKey, setApiKey] = useState(''); const [baseUrl, setBaseUrl] = useState(presets[0].baseUrl); const [model, setModel] = useState(presets[0].model);
  const load = async () => { setLoading(true); try { const response = await fetch('/api/ai-settings', { cache: 'no-store' }); const value = await response.json() as ResponseData; if (!response.ok) throw new Error(value.error || '读取失败'); setData({ ...value, source: value.source === 'none' ? 'none' : 'system' }); setPreferences(value.preferences || defaultPreferences); } catch (error) { toast.error(error instanceof Error ? error.message : '读取失败'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const reset = () => { setEditingId(''); setName(''); setProvider('DeepSeek'); setApiKey(''); setBaseUrl(presets[0].baseUrl); setModel(presets[0].model); setShowForm(true); };
  const edit = (profile: Profile) => { setEditingId(profile.id); setName(profile.name); setProvider(profile.provider); setApiKey(''); setBaseUrl(profile.baseUrl); setModel(profile.model); setShowForm(true); };
  const request = async (action: string, extra: Record<string, unknown> = {}) => { setWorking(action); try { const response = await fetch('/api/ai-settings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, profileId: editingId, name, provider, apiKey, baseUrl, model, ...extra }) }); const value = await response.json() as { error?: string; message?: string }; if (!response.ok) throw new Error(value.error || '操作失败'); toast.success(value.message || (action === 'test' ? '连接成功' : '设置已保存')); if (action !== 'test') { setShowForm(false); await load(); } } catch (error) { toast.error(error instanceof Error ? error.message : '操作失败'); } finally { setWorking(''); } };
  const remove = async (profile: Profile) => { if (!confirm(`确定删除“${profile.name}”吗？`)) return; setWorking(profile.id); try { const response = await fetch(`/api/ai-settings?profileId=${encodeURIComponent(profile.id)}`, { method: 'DELETE' }); if (!response.ok) throw new Error('删除失败'); toast.success('模型配置已删除'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : '删除失败'); } finally { setWorking(''); } };
  const savePreferences = async () => { setWorking('preferences'); try { const response = await fetch('/api/ai-settings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'preferences', preferences }) }); const value = await response.json() as { error?: string }; if (!response.ok) throw new Error(value.error || '保存失败'); toast.success('个性化设置已保存'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : '保存失败'); } finally { setWorking(''); } };

  return <div className="min-h-screen bg-[#F5F6F8] pb-10"><ManagePageHeader title="AI 配置" description="管理多个模型，并设置默认与备用模型" action={<button onClick={reset} className="flex items-center gap-1 rounded-lg bg-[#1E5AA8] px-3 py-2 text-xs text-white"><Plus className="h-4 w-4"/>新增模型</button>}/><main className="mx-auto max-w-3xl space-y-4 p-4">
    <section className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><div className="rounded-xl bg-[#E8F0FE] p-2.5 text-[#1E5AA8]"><Bot className="h-5 w-5"/></div><div><h2 className="font-semibold">模型列表</h2><p className="mt-1 text-xs leading-5 text-gray-400">默认模型用于 AI 问答；备用模型将在后续自动切换阶段启用。API Key 均加密保存。</p></div></div></section>
    {loading ? <div className="py-12 text-center text-gray-400"><Loader2 className="mx-auto h-5 w-5 animate-spin"/></div> : data.profiles.length === 0 ? <div className="rounded-2xl bg-white py-14 text-center text-sm text-gray-400">暂无模型配置，请点击“新增模型”</div> : <div className="space-y-3">{data.profiles.map((profile) => <section key={profile.id} className={`rounded-2xl border bg-white p-4 shadow-sm ${profile.id === data.activeProfileId ? 'border-[#1E5AA8]' : 'border-transparent'}`}><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{profile.name}</h3>{profile.id === data.activeProfileId && <span className="rounded-full bg-green-50 px-2 py-0.5 text-xs text-green-600">默认</span>}{profile.id === data.fallbackProfileId && <span className="rounded-full bg-amber-50 px-2 py-0.5 text-xs text-amber-600">备用</span>}{profile.readOnly && <span className="text-xs text-gray-400">环境变量</span>}</div><p className="mt-1 text-sm text-gray-600">{profile.provider} · {profile.model}</p><p className="mt-1 truncate text-xs text-gray-400">{profile.baseUrl} · {profile.apiKeyHint}</p></div>{!profile.readOnly && <div className="flex gap-1"><button onClick={() => edit(profile)} className="rounded-lg p-2 text-gray-400 hover:bg-blue-50"><Pencil className="h-4 w-4"/></button><button onClick={() => void remove(profile)} className="rounded-lg p-2 text-red-400 hover:bg-red-50"><Trash2 className="h-4 w-4"/></button></div>}</div>{!profile.readOnly && <div className="mt-3 flex flex-wrap gap-2">{profile.id !== data.activeProfileId && <button onClick={() => void request('activate', { profileId: profile.id })} className="rounded-lg bg-[#E8F0FE] px-3 py-1.5 text-xs text-[#1E5AA8]">设为默认</button>}<button onClick={() => void request('fallback', { profileId: data.fallbackProfileId === profile.id ? '' : profile.id })} disabled={profile.id === data.activeProfileId} className="rounded-lg bg-amber-50 px-3 py-1.5 text-xs text-amber-700 disabled:hidden">{data.fallbackProfileId === profile.id ? '取消备用' : '设为备用'}</button></div>}</section>)}</div>}
    {showForm && <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/45 p-4"><section className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-5 shadow-xl"><h2 className="font-semibold">{editingId ? '编辑模型' : '新增模型'}</h2><div className="mt-4 grid grid-cols-2 gap-2">{presets.map((preset) => <button key={preset.provider} onClick={() => { setProvider(preset.provider); setName(preset.provider); setBaseUrl(preset.baseUrl); setModel(preset.model); }} className={`rounded-lg border px-2 py-2 text-sm ${provider === preset.provider ? 'border-[#1E5AA8] bg-[#E8F0FE] text-[#1E5AA8]' : 'border-gray-200'}`}>{preset.provider}</button>)}</div><div className="mt-4 space-y-3"><label className="block text-sm">配置名称<input value={name} onChange={(e) => setName(e.target.value)} placeholder="例如：DeepSeek 日常问答" className="mt-1 h-10 w-full rounded-lg border px-3"/></label><label className="block text-sm">API Key<div className="relative mt-1"><input type={showKey ? 'text' : 'password'} value={apiKey} onChange={(e) => setApiKey(e.target.value)} placeholder={editingId ? '不修改可留空' : '请输入 API Key'} className="h-10 w-full rounded-lg border px-3 pr-10"/><button onClick={() => setShowKey(!showKey)} className="absolute right-2 top-2 p-1 text-gray-400">{showKey ? <EyeOff className="h-4 w-4"/> : <Eye className="h-4 w-4"/>}</button></div></label><label className="block text-sm">接口地址<input value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} className="mt-1 h-10 w-full rounded-lg border px-3"/></label><label className="block text-sm">模型名称<input value={model} onChange={(e) => setModel(e.target.value)} className="mt-1 h-10 w-full rounded-lg border px-3"/></label></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setShowForm(false)} className="rounded-lg px-4 py-2 text-sm text-gray-500">取消</button><button onClick={() => void request('test')} disabled={!!working} className="flex items-center gap-1 rounded-lg border border-[#1E5AA8] px-3 py-2 text-sm text-[#1E5AA8]"><TestTube2 className="h-4 w-4"/>测试</button><button onClick={() => void request('save')} disabled={!!working} className="flex items-center gap-1 rounded-lg bg-[#1E5AA8] px-4 py-2 text-sm text-white"><Save className="h-4 w-4"/>保存</button></div></section></div>}
    <section className="rounded-2xl bg-white p-4 shadow-sm"><h2 className="font-semibold">个性化设置</h2><p className="mt-1 text-xs text-gray-400">控制回答方式、统计口径和项目记忆。</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm">回答详细程度<select value={preferences.responseStyle} onChange={(e) => setPreferences({ ...preferences, responseStyle: e.target.value as Preferences['responseStyle'] })} className="mt-1 h-10 w-full rounded-lg border px-3"><option value="concise">简洁</option><option value="standard">标准</option><option value="detailed">详细</option></select></label><label className="text-sm">出勤默认口径<select value={preferences.attendanceMetric} onChange={(e) => setPreferences({ ...preferences, attendanceMetric: e.target.value as Preferences['attendanceMetric'] })} className="mt-1 h-10 w-full rounded-lg border px-3"><option value="both">人数 + 人天</option><option value="headcount">优先人数</option><option value="personDays">优先人天</option></select></label></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><label className="flex items-center justify-between rounded-xl bg-gray-50 p-3 text-sm">显示数据来源<input type="checkbox" checked={preferences.showSources} onChange={(e) => setPreferences({ ...preferences, showSources: e.target.checked })} className="h-4 w-4 accent-[#1E5AA8]"/></label><label className="flex items-center justify-between rounded-xl bg-gray-50 p-3 text-sm">项目长期记忆<input type="checkbox" checked={preferences.memoryEnabled} onChange={(e) => setPreferences({ ...preferences, memoryEnabled: e.target.checked })} className="h-4 w-4 accent-[#1E5AA8]"/></label></div><label className="mt-4 block text-sm">自定义回答要求<textarea value={preferences.customInstructions} onChange={(e) => setPreferences({ ...preferences, customInstructions: e.target.value })} maxLength={2000} placeholder="例如：日报结尾列出明日待办。" className="mt-1 min-h-24 w-full resize-y rounded-xl border p-3 text-sm"/></label><div className="mt-4 flex justify-end"><button disabled={working === 'preferences' || data.source !== 'system'} onClick={() => void savePreferences()} className="flex items-center gap-1 rounded-lg bg-[#1E5AA8] px-4 py-2 text-sm text-white disabled:opacity-40"><Save className="h-4 w-4"/>保存个性化设置</button></div>{data.source !== 'system' && <p className="mt-2 text-right text-xs text-amber-600">请先新增一个页面模型配置</p>}</section>
    <AiAbilitiesPanel value={preferences.abilities} onChange={(abilities) => setPreferences({ ...preferences, abilities })} onSave={() => void savePreferences()} saving={working === 'preferences'}/>
    <ProjectMemoryManager enabled={preferences.memoryEnabled}/>
    <AiUsageSummary value={data.usage}/>
  </main></div>;
}
